import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },  header: {
    alignItems: 'center',
    padding: 30,
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  selectedColor: {
    width: 100,
    height: 100,
    borderRadius: 50,
    marginTop: 20,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  colorCode: {
    fontSize: 16,
    fontWeight: '600',
    color: '#34495e',
  },
  colorName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2c3e50',
    marginBottom: 5,
  },
  colorType: {
    fontSize: 14,
    fontWeight: '500',
    color: '#e74c3c',
    marginTop: 5,
  },
  rayTypeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 5,
  },
  rayTypeIcon: {
    fontSize: 16,
    marginRight: 8,
  },
  wavelengthText: {
    fontSize: 12,
    color: '#7f8c8d',
    fontStyle: 'italic',
    marginTop: 2,
  },
  colorGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    padding: 10,
    gap: 10,
  },
  colorBox: {
    width: 50,
    height: 50,
    borderRadius: 25,
    margin: 3,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    overflow: 'hidden',
  },
  gradientBox: {
    width: '100%',
    height: '100%',
    borderRadius: 25,
  },
  infraredPattern: {
    width: 50,
    height: 50,
    borderRadius: 25,
    margin: 3,
    borderWidth: 2,
    borderColor: '#FF4500',
    borderStyle: 'dashed',
    shadowColor: '#FF0000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 6,
    overflow: 'hidden',
  },
  ultravioletPattern: {
    width: 50,
    height: 50,
    borderRadius: 25,
    margin: 3,
    borderWidth: 2,
    borderColor: '#8A2BE2',
    shadowColor: '#9400D3',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 6,
    overflow: 'hidden',
  },
  xrayPattern: {
    width: 50,
    height: 50,
    borderRadius: 25,
    margin: 3,
    borderWidth: 3,
    borderColor: '#C0C0C0',
    borderStyle: 'dotted',
    shadowColor: '#708090',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 7,
    overflow: 'hidden',
  },
  gammaPattern: {
    width: 50,
    height: 50,
    borderRadius: 25,
    margin: 3,
    borderWidth: 2,
    borderColor: '#FFD700',
    shadowColor: '#FFA500',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.6,
    shadowRadius: 6,
    elevation: 8,
    overflow: 'hidden',
  },
  cosmicPattern: {
    width: 50,
    height: 50,
    borderRadius: 25,
    margin: 3,
    borderWidth: 3,
    borderColor: '#191970',
    shadowColor: '#000080',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.7,
    shadowRadius: 7,
    elevation: 9,
    overflow: 'hidden',
  },
  selectedBorder: {
    borderWidth: 4,
    borderColor: '#2c3e50',
  },
  conversionButton: {
    backgroundColor: '#9b59b6',
    borderRadius: 15,
    padding: 15,
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },  conversionButtonText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  sectionContainer: {
    marginVertical: 15,
    paddingHorizontal: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2c3e50',
    textAlign: 'center',
    marginBottom: 15,
    backgroundColor: '#ecf0f1',
    padding: 10,
    borderRadius: 8,
  },
  wavelengthInfo: {
    fontSize: 14,
    color: '#7f8c8d',
    textAlign: 'center',
    marginBottom: 10,
    fontStyle: 'italic',
  },
  bottomPadding: {
    height: 30,
  },
});
